[package]
name = "lib_test"
version = "0.1.0"
edition = "2021"

[dependencies]
reqstreams = { git = "https://github.com/Saqib839/Substreams_rust_sdk.git",  rev = "be15bb4a96a6fb59dd397bc8a0484179dab37bce" }
anyhow = "1"
async-stream = "0.3"
futures03 = { version = "0.3.1", package = "futures", features = ["compat"] }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.27", features = [
    "time",
    "sync",
    "macros",
    "test-util",
    "rt-multi-thread",
    "parking_lot",
    "full"
] }
tokio-stream = { version = "0.1", features = ["sync"] }
tokio-retry = "0.3"
tonic = { version = "0.12", features = ["gzip", "tls-roots"] }
prost = "0.13"
prost-types = "0.13"
thiserror = "1"
chrono = "0.4.38"
regex = "1.11.1"
lazy_static = "1.5.0"
semver = "1.0.23"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"